### ISSUE TITLE
Issue with dependencies

### ISSUE THREAD

**Issue by tjvantoll** [NativeScript/template-hello-world-ng#10]
Ping @vchimev. Ever since 701fe73cbfeaa6f4ef92fa3ef9a1f7e5ca46f4b0 it appears that there are dependencies missing when you use this repo as a template.

To recreate this run:

```
tns create my-app-name --template https://github.com/NativeScript/template-hello-world-ng
cd my-app-name
tns install
tns run android
```

You’ll get a bunch of TypeScript errors like `app/app.component.ts(1,25): error TS2307: Cannot find module 'angular2/core'.` because `node_modules/angular2` is not there. This was also reported in https://github.com/tjvantoll/nativescript-angular-guide/pull/4.

**Comment by vchimev** [comment]
Thanks @tjvantoll,

I merged PR https://github.com/NativeScript/template-hello-world-ng/pull/11 to restore the *angular2* and *tns-core-modules* dependencies. Also @hdeshev pushed a new version of the package to npm.


I would suggest prior to 2.0.0 instead of
```
tns create my-app-name --template https://github.com/NativeScript/template-hello-world-ng
```
to use
```
tns create my-app-name --template tns-template-hello-world-ng
```
which will create a project using the latest *tns-template-hello-world-ng* package from npm.

**Comment by tjvantoll** [comment]
Thanks @vchimev!

I only used that syntax because I didn’t realize this template had been published. I just tried it out and it works great so I’ll update my notes.
